[build]
    command = "chmod +x ./build.sh && ./build.sh"
    functions = "functions"
    publish = "assets"

[build.environment]
    GO_IMPORT_PATH = "github.com/LamichhaneBibek/petpal-go"
    GO111MODULE = "on"

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/gateway/:splat"
    status = 200
